// Reducer: a function that returns a piece of the applications state

/*

  // Application State - Generated by reducers
  {
    books: [{title: 'Harry Potter'}, {title: 'JavaScript'}],  // Books Reducer
    activeBook: {title: 'JavaScript: The Good Parts'}         // ActiveBook Reducer
  }

*/

export default function() {
  return [
    { title: 'JavaScript: The Good Parts', pages: 101 },
    { title: 'Harry Potter ', pages: 39 },
    { title: 'The Dark Tower', pages: 85 },
    { title: 'Eloquent Ruby', pages: 1 }
  ]
}
